import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

const generate404Plugin = (): Plugin => {
  return {
    name: 'vite-plugin-generate-404',
    writeBundle() {
      const distPath = path.resolve(__dirname, 'dist');
      const indexPath = path.join(distPath, 'index.html');
      const notFoundPath = path.join(distPath, '404.html');

      // 直接复制 index.html 为 404.html
      fs.copyFile(indexPath, notFoundPath, (err) => {
        if (err) {
          console.error(err);
          return;
        }
        console.log('404.html has been generated by copying index.html!');
      });
    },
  };
};

export default generate404Plugin;
